import { useTexture } from "@react-three/drei";

const vintageStickers = [
    "a_tree.png",
    "angels_on_clouds.png",
    "bouque_2.png",
    "bouque.png",
    "bunnies_swinging.png",
    "catz_1.png",
    "catz_2.png",
    "catz_3.png",
    "catz_4.png",
    "clouds_1.png",
    "clouds_2.png",
    "clouds_3.jpg",
    "clouds_decor.png",
    "crown.png",
    "cupid_god.png",
    "deer_resting.png",
    "deer_resting_mini.png",
    "decor.png",
    "dream_hands.png",
    "dream_hands_1.png",
    "dreamy_us.png",
    "empty_yet_full.png",
    "feather_decor.png",
    "feather_hand.png",
    "flower_blue.png",
    "flower_decor.png",
    "flower_decor_1.png",
    "flower_decor_2.png",
    "flower_decor_3.png",
    "flower_guy.png",
    "foxy_me.png",
    "galaxy_1.png",
    "galaxy_2.jpg",
    "looking_down.png",
    "love_bird.png",
    "love_letter.png",
    "mushrooms.png",
    "nova_falling.png",
    "our_faith.png",
    "peacock.png",
    "rabbit_sorcerer.jpg",
    "rabbit_violinist.png",
    "reaching_heavens.png",
    "rose.png",
    "roses_side.png",
    "ruru_dancing.png",
    "ruru_eyes.png",
    "ruru_no_mercy.png",
    "ruru_reading.png",
    "ruru_smiling.png",
    "spider_me.png",
    "stars_decor.png",
    "sun_moon.png",
    "teddy.png",
    "us_as_catzz.png",
    "vase_1.png",
    "waterfall.png",
    "who_might_it_be.png",
    "wings.png",
    "wine_1.png",
    "wine_2.png",
];

const animeStickers = Array.from({ length: 48 }, (_, i) => `img_${i + 1}.jpg`);

export function StickerPreload() {
    useTexture.preload(vintageStickers.map(s => `/ruru/${s}`));
    useTexture.preload(animeStickers.map(s => `/anime/${s}`));
    return null;
}
