const Left = { x: -window.innerWidth / 2 - 300, y: 117, scale: 0, opacity: 0, zIndex: 100 }
const Right = { x: window.innerWidth / 2 + 300, y: 117, scale: 0, opacity: 0, zIndex: 100}
const Top = { x: -106, y: -window.innerHeight / 2 - 300, scale: 0, opacity: 0, zIndex: 100 }
const Down = { x: -106, y: window.innerHeight / 2 + 300, scale: 0, opacity: 0, zIndex: 100}
const Center = { x: -106, y: 117, scale: 0, opacity: 0, zIndex: 100}

const sceneOne = {
    title: {
        text: "A Perfect Past",
        from: { y: 40, opacity: 0 },
        to: { y: 0, opacity: 1 },
        exit: { y: -40, opacity: 0 },
        hold: 1.2,
    },
    items: [
        {
            type: "image",
            id: "looking_down.pn",
            path: "/ruru/looking_down.png",
            from: Top,
            to: { x: 580, y: -210, scale: 0.14, opacity: 1 },
            hold: 2,
            exit: { x: 580, y: -198, scale: 0.12, opacity: 0 },
        },
        {
            type: "image",
            id: "reaching_heavens.png",
            path: "/ruru/reaching_heavens.png",
            from: Down,
            to: { x: -129, y: 146, scale: 0.15, opacity: 1 },
            hold: 2,
            exit: { x: -100, y: 146, scale: 0.17, opacity: 0, },
        },
        {
            type: "image",
            id: "sun.png",
            path: "/ruru/sun.png",
            from: Top,
            to: { x: 117, y: -172, scale: 0.2, opacity: 1 },
            hold: 2,
            exit: {  x: 117, y: -172, scale: 0.12,  opacity: 0, },
        },
        {
            type: "image",
            id: "clouds_1.jpg",
            path: "/ruru/clouds_1.png",
            from: { x: -106, y: 117, scale: 2, opacity: 0},
            to: { x: 0, y: 0, scale: 1.50, opacity: 0.3, zIndex: 2 },
            hold: 2,
            exit: { x: 0, y: 0, scale: 1.50, opacity: 0, zIndex: 2 },
        },
        {
            type: "image",
            id: "wine_1.png",
            path: "/ruru/wine_1.png",
            from: Left,
            to: { x: -463, y: -219, scale: 0.17, opacity: 1 },
            hold: 2,
            exit: { x: -463, y: -219, scale: 0.19, opacity: 0, },
        },
        {
            type: "text",
            id: "scene1-line",
            text: "Forever felt closer than it truly was.",
            from: { x: 71, y: -85, opacity: 0 },
            to: { x: 80, y: 50, opacity: 1 },
            hold: 2,
            exit: { y: -80, opacity: 0 },
        },
    ]
};

const sceneTwo = {
    title: {
        text: "The Moment She Let Go",
        from: { y: 40, opacity: 0 },
        to: { y: 0, opacity: 1 },
        exit: { y: -40, opacity: 0 },
        hold: 1.4,
    },
    items: [
        {
            type: "image",
            id: "galaxy_1.png",
            path: "/ruru/galaxy_1.png",
            from: Left,
            to: { x: -596, y: -203, scale: 0.18, opacity: 1 },
            hold: 2,
            exit: { x: -1000, y: -203, scale: 0.15, opacity: 0 },
        },
        {
            type: "image",
            id: "crown.png",
            path: "/ruru/crown.png",
            from: Left,
            to: { x: -318, y: -173, scale: 0.10, opacity: 1 },
            hold: 2,
            exit: { x: -318, y: -173, scale: 0.13, opacity: 0 },
        },
        {
            type: "image",
            id: "ruru_no_mercy.png",
            path: "/ruru/ruru_no_mercy.png",
            from: Left,
            to: { x: -347, y: -121, scale: 0.10, opacity: 1 },
            hold: 2.2,
            exit: { x: -347, y: -121, scale: 0.10, opacity: 0 },
        },
        {
            type: "image",
            id: "nova_halo.png",
            path: "/ruru/nova_halo.png",
            from: Top,
            to: { x: 40, y: 100, scale: 0.21, opacity: 1 },
            hold: 2,
            exit: { x: 490, y: 370, scale: 0.25, opacity: 0 },
        },
        {
            type: "image",
            id: "nova_falling.png",
            path: "/ruru/nova_falling.png",
            from: Top,
            to: { x: 41, y: 181, scale: 0.11, opacity: 1 },
            hold: 2,
            exit: { x: 483, y: 450, scale: 0.13, opacity: 0 },
        },
        {
            type: "image",
            id: "roses_side.png",
            path: "/ruru/roses_side.png",
            from: Right,
            to: { x: 639, y: 231, scale: 0.10, opacity: 1 },
            hold: 2,
            exit: { x: 639, y: 231, scale: 0.12, opacity: 0 },
        },
        {
            type: "text",
            id: "scene2-line-1",
            text: "She didn’t raise a weapon.",
            from: Top,
            to: { x: 266, y: -300, opacity: 1, scale: 1 },
            hold: 1.8,
            exit: { x: 266, y: -300, opacity: 0 },
        },
        {
            type: "text",
            id: "scene2-line-2",
            text: "She simply said the truth he was hiding from.",
            from: Right,
            to: { x: 120, y: -220, opacity: 1, scale: 1 },
            hold: 2.2,
            exit: { x: 120, y: -220, opacity: 0 },
        },
        {
            type: "text",
            id: "scene2-line-3",
            text: "And in that moment, Nova realized — ", // — he was already dead.",
            from: Down,
            to: { x: 120, y: -150, opacity: 1, scale: 1 },
            hold: 2.6,
            exit: { x: 300, y: -150, opacity: 0 },
        },
    ],
};

const sceneThree = {
    title: {
        text: "A tragedy and a never future",
        from: { y: 40, opacity: 0 },
        to: { y: 0, opacity: 1 },
        exit: { y: -40, opacity: 0 },
        hold: 1.2,
    },
    items: [
        {
            type: "image",
            id: "dreamy_us.png",
            path: "/ruru/dreamy_us.png",
            from: Center,
            to: { x: -106, y: 117, scale: 0.24, opacity: 1 },
            hold: 2,
            exit: { x: -106, y: 117, scale: 0.24, opacity: 0 },
        },
        {
            type: "image",
            id: "cupid_god.png",
            path: "/ruru/cupid_god.png",
            from: Left,
            to: { x: 631, y: 220, scale: 0.17, opacity: 1 },
            hold: 2,
            exit: { x: -631, y: 220, scale: 0.17, opacity: 0, },
        },
        {
            type: "image",
            id: "sun_moon.png",
            path: "/ruru/sun_moon.png",
            from: Top,
            to: { x: 117, y: -172, scale: 0.12, opacity: 1 },
            hold: 2,
            exit: {  x: 117, y: -172, scale: 0.12,  opacity: 0, },
        },
        {
            type: "image",
            id: "clouds_3.jpg",
            path: "/ruru/clouds_3.jpg",
            from: { x: -106, y: 117, scale: 2, opacity: 0, zIndex: 100},
            to: { x: 0, y: 0, scale: 1.5, opacity: 1, zIndex: 2 },
            hold: 2,
            exit: { x: 0, y: 0, scale: 1.50, opacity: 0, zIndex: 2 },
        },
        {
            type: "image",
            id: "love_bird.png",
            path: "/ruru/love_bird.png",
            from: Left,
            to: { x: -564, y: -281, scale: 0.10, opacity: 1 },
            hold: 2,
            exit: { x: -564, y: -281, scale: 0.10, opacity: 0, },
        },
        {
            type: "text",
            id: "scene2-line",
            text: "Thought forever had no end.",
            from: { x: 71, y: -85, opacity: 0 },
            to: { x: 50, y: 100, opacity: 1 },
            hold: 2,
            exit: { y: -80, opacity: 0 },
        },
    ]
};

const sceneFour = {
    title: {
        text: "What Stayed",
        from: { y: 40, opacity: 0 },
        to: { y: 0, opacity: 1 },
        exit: { y: -40, opacity: 0 },
        hold: 1.2,
    },
    items: [
        {
            type: "image",
            id: "nova_hut.png",
            path: "/ruru/nova_hut.png",
            from: Right,
            to: { x: 489, y: 204, scale: 0.23, opacity: 1 },
            hold: 2,
            exit: { x: 489, y: 204, scale: 0.23, opacity: 0 },
        },
        {
            type: "image",
            id: "foxy_me.png",
            path: "/ruru/foxy_me.png",
            from: Down,
            to: { x: 123, y: 297, scale: 0.10, opacity: 1 },
            hold: 2,
            exit: { x: 123, y: 297, scale: 0.10, opacity: 0 },
        },
        {
            type: "image",
            id: "a_tree.png",
            path: "/ruru/a_tree.png",
            from: Left,
            to: { x: -526, y: 64, scale: 0.23, opacity: 1 },
            hold: 2,
            exit: { x: -526, y: 64, scale: 0.23, opacity: 0 },
        },
        {
            type: "image",
            id: "flower_decor_1.png",
            path: "/ruru/flower_decor_1.png",
            from: Left,
            to: { x: -714, y: -206, scale: 0.10, opacity: 1 },
            hold: 2,
            exit: { x: -714, y: -206, scale: 0.10, opacity: 0 },
        },
        {
            type: "image",
            id: "wind.png",
            path: "/ruru/wind.png",
            from: Right,
            to: { x: 257, y: -105, scale: 0.23, opacity: 1 },
            hold: 2,
            exit: { x: 257, y: -105, scale: 0.23, opacity: 0 },
        },
        {
            type: "image",
            id: "flower_decor_3.png",
            path: "/ruru/flower_decor_3.png",
            from: Right,
            to: { x: 629, y: -186, scale: 0.19, opacity: 1 },
            hold: 2,
            exit: { x: 629, y: -186, scale: 0.19, opacity: 0 },
        },
        {
            type: "image",
            id: "flower_guy.png",
            path: "/ruru/flower_guy.png",
            from: Down,
            to: { x: -111, y: 143, scale: 0.14, opacity: 1 },
            hold: 2,
            exit: { x: -111, y: 143, scale: 0.14, opacity: 0 },
        },
        {
            type: "text",
            id: "scene4-line-1",
            text: "What stayed, stayed.",
            from: { y: 60, opacity: 0 },
            to: { x: -39, y: -308, opacity: 1 },
            hold: 2,
            exit: { x: -39, y: -308, scale: 2, opacity: 0 },
        },
        {
            type: "text",
            id: "scene4-line-2",
            text: "Without needing to be remembered.",
            from: { y: 80, opacity: 0 },
            to: { x: -39, y: -272, opacity: 1 },
            hold: 2.2,
            exit: { x: -39, y: -272, scale: 2, opacity: 0 },
        },
    ],
};

const sceneFive = {
    title: {
        text: "What's Left",
        from: { y: 40, opacity: 0 },
        to: { y: 0, opacity: 1 },
        exit: { y: -40, opacity: 0 },
        hold: 1.2,
    },
    items: [
        {
            type: "image",
            id: "ruru_angel.png",
            path: "/ruru/ruru_angel.png",
            from: Top,
            to: { x: -599, y: -76, scale: 0.10, opacity: 1 },
            hold: 2,
            exit: { x: -599, y: -76, scale: 0.10, opacity: 0 },
        },
        {
            type: "image",
            id: "catz_1.png",
            path: "/ruru/catz_1.png",
            from: Down,
            to: { x: 100, y: 178, scale: 0.05, opacity: 1 },
            hold: 2,
            exit: { x: 100, y: 178, scale: 0.05, opacity: 0 },
        },
        {
            type: "image",
            id: "rabbit_violinist.png",
            path: "/ruru/rabbit_violinist.png",
            from: Right,
            to: { x: 197, y: 291, scale: 0.10, opacity: 1 },
            hold: 2,
            exit: { x: 197, y: 291, scale: 0.10, opacity: 0 },
        },
        {
            type: "image",
            id: "ruru.png",
            path: "/ruru/ruru.png",
            from: Down,
            to: { x: 34, y: 206, scale: 0.10, opacity: 1 },
            hold: 2,
            exit: { x: 34, y: 206, scale: 0.10, opacity: 0 },
        },
        {
            type: "image",
            id: "ruru_books.png",
            path: "/ruru/ruru_books.png",
            from: Down,
            to: { x: -200, y: 241, scale: 0.1, opacity: 1 },
            hold: 2,
            exit: { x: -200, y: 241, scale: 0.1, opacity: 0 },
        },
        {
            type: "image",
            id: "deer_resting_mini.png",
            path: "/ruru/deer_resting_mini.png",
            from: Right,
            to: { x: 346, y: 342, scale: 0.52, opacity: 1 },
            hold: 2,
            exit: { x: 346, y: 342, scale: 0.52, opacity: 0 },
        },
        {
            type: "image",
            id: "waterfall.png",
            path: "/ruru/waterfall.png",
            from: Right,
            to: { x: 623, y: 0, scale: 0.23, opacity: 1 },
            hold: 2,
            exit: { x: 623, y: 0, scale: 0.23, opacity: 0 },
        },
        {
            type: "image",
            id: "flower_decor_2.png",
            path: "/ruru/flower_decor_2.png",
            from: Left,
            to: { x: -551, y: -272, scale: 0.16, opacity: 1 },
            hold: 2,
            exit: { x: -551, y: -272, scale: 0.16, opacity: 0 },
        },
        {
            type: "image",
            id: "bunnies_swinging.png",
            path: "/ruru/bunnies_swinging.png",
            from: Top,
            to: { x: -174, y: -236, scale: 0.10, opacity: 1 },
            hold: 2,
            exit: { x: -174, y: -236, scale: 0.10, opacity: 0 },
        },
        {
            type: "image",
            id: "ruru_window.png",
            path: "/ruru/ruru_window.png",
            from: Top,
            to: { x: 197, y: -178, scale: 0.14, opacity: 1 },
            hold: 2,
            exit: { x: 197, y: -178, scale: 0.14, opacity: 0 },
        },
        {
            type: "image",
            id: "ruru_hut.png",
            path: "/ruru/ruru_hut.png",
            from: Left,
            to: { x: -574, y: 108, scale: 0.14, opacity: 1 },
            hold: 2,
            exit: { x: -574, y: 108, scale: 0.14, opacity: 0 },
        },
        {
            type: "text",
            id: "scene5-line-1",
            text: "What left, became distance.",
            from: { y: 60, opacity: 0 },
            to: { x: -300, y: -25, opacity: 1 },
            hold: 2,
            exit: { y: -60, opacity: 0 },
        },
        {
            type: "text",
            id: "scene5-line-2",
            text: "Without ever turning back.",
            from: { y: 80, opacity: 0 },
            to: { x: -300, y: 0, opacity: 1 },
            hold: 2.2,
            exit: { y: -80, opacity: 0 },
        },
    ],
};

export const scenes = [
    sceneOne, sceneTwo, sceneThree,
    sceneFour, sceneFive,
];
